[options]
    colorscheme = "NeoSolarized"
    colorscheme_bg = "light"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    default_indent = 4

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "colorscheme"

# [[layers]]
  # name = "lsp"
  # filetypes = [
    # "rust"
  # ]

[[layers]]
  name = "lang#rust"
  recommended_style = true
  format_on_save = true
  rustfmt_cmd = "/usr/bin/rustfmt"
  racer_cmd = "/usr/bin/racer"

[layers.override_cmd]
  rust = ["rls"]

[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "nil"
    auto-completion-tab-key-behavior = "smart"
    autocomplete_parens = false

[[layers]]
    name = "shell"
    default_position = "bottom"
    default_height = 30

#[options]
#    bootstrap_before = 'myspacevim#before'
#    bootstrap_after = 'myspacevim#after'
